fixtures:
    symlinks:
      panopta: "#{source_dir}"
    repositories:
      apt:
        repo: https://github.com/puppetlabs/puppetlabs-apt.git
        ref: 4.3.2
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.1.0
    forge_modules:
